export enum RideStatus {
    PENDING = "PENDING",
    DRIVER_ACCEPTED = "DRIVER_ACCEPTED",
    DRIVER_CANCELED = "DRIVER_CANCELED",
    ON_GOING = "ON_GOING",
    COMPLETED = "COMPLETED",
    CANCELED = "CANCELED",
  }
  